-- Public profile data is separate from Supabase Auth credentials.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  role text not null default 'MORADOR' check (role in ('ADMIN', 'SINDICO', 'MORADOR', 'VISUALIZADOR')),
  created_at timestamptz not null default now()
);

create table public.reclamacoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  apartamento text not null,
  assunto text not null,
  descricao text not null,
  data date not null default current_date,
  lido boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.property_ads (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('Venda', 'Aluguel')),
  location text not null,
  price text not null,
  description text not null,
  photos text[] not null default '{}',
  published boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.service_ads (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  phone text not null,
  description text not null,
  photo text,
  published boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.financial_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  type text not null check (type in ('Entrada', 'Saída')),
  description text not null,
  category text not null,
  value numeric(12, 2) not null check (value >= 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', new.email));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'ADMIN'
  );
$$;

alter table public.profiles enable row level security;
alter table public.reclamacoes enable row level security;
alter table public.property_ads enable row level security;
alter table public.service_ads enable row level security;
alter table public.financial_entries enable row level security;

create policy "Users can read their own profile"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

create policy "Admins can manage profiles"
on public.profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Users can create their own complaints"
on public.reclamacoes for insert
to authenticated
with check (user_id = auth.uid());

create policy "Users can read their own complaints"
on public.reclamacoes for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "Admins can manage complaints"
on public.reclamacoes for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete complaints"
on public.reclamacoes for delete
to authenticated
using (public.is_admin());

create policy "Anyone can read published properties"
on public.property_ads for select
using (published = true or public.is_admin());

create policy "Admins can manage properties"
on public.property_ads for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Anyone can read published services"
on public.service_ads for select
using (published = true or public.is_admin());

create policy "Admins can manage services"
on public.service_ads for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage financial entries"
on public.financial_entries for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create index reclamacoes_user_id_idx on public.reclamacoes(user_id);
create index property_ads_published_idx on public.property_ads(published);
create index service_ads_published_idx on public.service_ads(published);
