create table if not exists public.package_deliveries (
  id bigint generated by default as identity primary key,
  recipient_name text not null,
  apartment text not null,
  block text not null check (block in ('Bloco A', 'Bloco B')),
  carrier text not null,
  tracking_code text,
  received_at timestamptz not null default now(),
  status text not null default 'RECEBIDA' check (status in ('RECEBIDA', 'NOTIFICADA', 'ENTREGUE')),
  notes text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

alter table public.package_deliveries enable row level security;

drop policy if exists "Admins can read package deliveries" on public.package_deliveries;
create policy "Admins can read package deliveries"
on public.package_deliveries for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can create package deliveries" on public.package_deliveries;
create policy "Admins can create package deliveries"
on public.package_deliveries for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "Admins can update package deliveries" on public.package_deliveries;
create policy "Admins can update package deliveries"
on public.package_deliveries for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete package deliveries" on public.package_deliveries;
create policy "Admins can delete package deliveries"
on public.package_deliveries for delete
to authenticated
using (public.is_admin());

create index if not exists package_deliveries_status_idx on public.package_deliveries(status);
create index if not exists package_deliveries_received_at_idx on public.package_deliveries(received_at desc);