create table public.financial_documents (
  id bigint generated by default as identity primary key,
  file_name text not null,
  storage_path text not null unique,
  reference_month integer not null check (reference_month between 1 and 12),
  reference_year integer not null check (reference_year between 2000 and 2100),
  status text not null default 'PENDING' check (status in ('PENDING', 'IMPORTED', 'REVIEW')),
  extracted_text text,
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

alter table public.financial_entries
  add column if not exists document_id bigint references public.financial_documents(id) on delete set null;

create or replace function public.is_finance_manager()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('ADMIN', 'SINDICO')
  );
$$;

alter table public.financial_documents enable row level security;

create policy "Authenticated users can read financial documents"
on public.financial_documents for select
to authenticated
using (true);

create policy "Finance managers can manage financial documents"
on public.financial_documents for all
to authenticated
using (public.is_finance_manager())
with check (public.is_finance_manager());

drop policy if exists "Authenticated users can create financial entries" on public.financial_entries;
drop policy if exists "Authenticated users can update financial entries" on public.financial_entries;
drop policy if exists "Authenticated users can delete financial entries" on public.financial_entries;

create policy "Finance managers can create financial entries"
on public.financial_entries for insert
to authenticated
with check (public.is_finance_manager());

create policy "Finance managers can update financial entries"
on public.financial_entries for update
to authenticated
using (public.is_finance_manager())
with check (public.is_finance_manager());

create policy "Finance managers can delete financial entries"
on public.financial_entries for delete
to authenticated
using (public.is_finance_manager());

insert into storage.buckets (id, name, public)
values ('financial-documents', 'financial-documents', false)
on conflict (id) do nothing;

create policy "Finance managers can upload financial documents"
on storage.objects for insert
to authenticated
with check (bucket_id = 'financial-documents' and public.is_finance_manager());

create policy "Authenticated users can read financial documents files"
on storage.objects for select
to authenticated
using (bucket_id = 'financial-documents');

create policy "Finance managers can delete financial documents files"
on storage.objects for delete
to authenticated
using (bucket_id = 'financial-documents' and public.is_finance_manager());